### ISSUE TITLE
Module not found: Error: Can't resolve 'silk-swipe'

### ISSUE THREAD

**Issue by xzblog** [houyulei/Tabs#1]
我在用你的这个包的时候遇到了 Can't resolve 'silk-swipe' 这个错， 我用npm安装了silk-swipe也依旧报这个错

**Comment by CodingMonkeyzh** [comment]
测试了下， 是可以安装的。  检查下你的 `~/.npmrc` 文件配置
```bash
npm i silk-swipe  
npm WARN rc-notification@1.4.3 No license field.

+ silk-swipe@2.0.4
added 1 package in 4.313s
```
![image](https://user-images.githubusercontent.com/2787386/27596587-8e7927c2-5b92-11e7-8c40-deeb5f9c7f0c.png)

**Comment by CodingMonkeyzh** [comment]
@xzblog import 'silk-swipe' 报错的原因是 `silk-swipe` 包自身的错误（没有发布 `lib/swipe.js`）：
![image](https://user-images.githubusercontent.com/2787386/27597860-3bc424ba-5b96-11e7-8f91-fa1ffa594e65.png)

**Comment by kanily** [comment]
ERROR in ./~/silk-react-swipe/lib/index.js
Module not found: Error: Cannot resolve module 'silk-swipe' in D:\backup\c\Desktop\workCode\qingyouxinli-react\node_modules\silk-react-swipe\lib
 @ ./~/silk-react-swipe/lib/index.js 37:17-38
  
how to reslove this problem ? thanks

**Comment by CodingMonkeyzh** [comment]
@developerYangli build the `lib/` by yourself
